# Generated by Django 4.1.4 on 2023-09-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postpub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puserid', models.IntegerField()),
                ('ptitle', models.CharField(max_length=50)),
                ('pdescription', models.CharField(max_length=200)),
                ('ptag', models.CharField(max_length=30)),
                ('pdate', models.DateTimeField()),
            ],
        ),
    ]
