# Generated by Django 4.1.4 on 2023-08-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('fileimage', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
