# Generated by Django 4.1.4 on 2023-08-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0003_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=200)),
                ('proprize', models.IntegerField()),
                ('companyname', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('expiry', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
