# Generated by Django 4.1.4 on 2023-08-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0004_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileimage',
            field=models.FileField(upload_to=''),
        ),
    ]
