# Generated by Django 4.1.4 on 2023-08-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0005_alter_fileupload_fileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileimage',
            field=models.FileField(upload_to='Calculator_app\\static'),
        ),
    ]
