# Generated by Django 4.1.4 on 2023-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0006_alter_fileupload_fileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioname', models.CharField(max_length=200)),
                ('audiofile', models.FileField(upload_to='Calculator_app\\static')),
                ('videoname', models.CharField(max_length=200)),
                ('videofile', models.FileField(upload_to='Calculator_app\\static')),
                ('pdfname', models.CharField(max_length=200)),
                ('pdffile', models.FileField(upload_to='Calculator_app\\static')),
            ],
        ),
    ]
