# Generated by Django 4.1.4 on 2023-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0007_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Malayalam', models.BooleanField(default=False)),
                ('English', models.BooleanField(default=False)),
                ('Hindi', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('kerala', 'Kerala'), ('tamil nadu', 'Tamil Nadu'), ('karnataka', 'Karnataka')], max_length=200)),
            ],
        ),
    ]
