# Generated by Django 4.1.4 on 2023-08-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator_app', '0008_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='select',
            old_name='name',
            new_name='fname',
        ),
    ]
