# Generated by Django 3.0.3 on 2020-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0004_auto_20200222_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('perno', models.CharField(max_length=20)),
                ('missedarea', models.CharField(max_length=1000)),
                ('my_content', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
