# Generated by Django 3.0.3 on 2020-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0006_addcriminals'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcriminalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('carea', models.CharField(max_length=800)),
                ('ctype', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='addcriminals',
        ),
    ]
