# Generated by Django 4.1.4 on 2023-09-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
