# Generated by Django 4.1.4 on 2023-09-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ptype', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='model_seller',
            name='photo',
            field=models.FileField(upload_to='ecommerce_app/static'),
        ),
    ]
