# Generated by Django 4.1.4 on 2023-09-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_remove_proadd_ptype_proadd_p_type_alter_proadd_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proadd',
            name='p_type',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Jewellery', 'Jewellery'), ('Electronic', 'Electronic')], max_length=200),
        ),
    ]
