# Generated by Django 4.1.4 on 2023-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_alter_proadd_p_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('pbrand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
