# Generated by Django 4.1.4 on 2023-09-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_wishmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishmodel',
            name='prod_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
