# Generated by Django 4.1.4 on 2023-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_wishmodel_prod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('pbrand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
