# Generated by Django 4.1.4 on 2023-09-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('u_address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
