# Generated by Django 4.1.4 on 2023-10-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_address_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('est_del_date', models.DateField(null=True)),
                ('products', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
